[package]
name = "protobuf-build"
version = "0.6.0"
authors = ["Nick Cameron <nrc@ncameron.org>"]
edition = "2018"
license = "Apache-2.0"
description = "Utility functions for generating Rust code from protobufs (using protobuf-rust or Prost)"

[dependencies]
protoc-rust = "2.0"
protoc-grpcio = "1.0.2"
grpcio-compiler = { path = "../grpc-rs/compiler" }
regex = "1.1"
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
bitflags = "1.0"
